
room_name: "EB"

points: 2

point:
  idx1:
    pos: [0, 0, 0] #坐标位
    level: 1 #层数
    area: [[-5,0,-5],[-5,0,5],[5,0,5],[5,0,-5]] #有效面积
    type: 0 #类型
  idx2:
    pos: [10, 0, 0]
    level: 1
    area: [[5,0,-5],[5,0,5],[15,0,5],[15,0,-5]]
    type: 0

connection:
  idx1:
    points:
      [[2,0.1]]
  idx2:
    points:
      [[1,0.1]]